version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.16
    steps:
      - setup_remote_docker:
          version: 20.10.2
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build --ssh=default --progress plain -t custom-alpine:latest .

workflows:
  docker:
    jobs:
      - build
